# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: roda-xaron
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Capoeira Cordão de Ouro
permalink: ":title/"
baseurl: "/rodaxaron" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jekyll

# Author Settings
author: RODA-XARON # add your name
author-img: cdo.png # add your photo
about-author: Capoeira Cordão de Ouro
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: yanivmo # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Build settings
markdown: kramdown
remote_theme: artemsheludko/flexible-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
